about/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('',views.about,name='about'),
]

blog/urls.py
from django.urls import path
from . import views
app_name = "blog"

urlpatterns = [
    path('',views.all_blogs,name='all_blogs'),
    path('<int:blog_id>/',views.detail,name='detail'),
]

project/urls.py
from django.urls import path
from . import views
app_name = "project"

urlpatterns = [
    path('',views.all_projects,name='all_projects'),
    path('<int:project_id>/',views.detail,name='detail'),
]

ryckee/urls.py
from django.contrib import admin
from django.urls import include,path
from django.conf.urls.static import static
from django.conf import settings
from home import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home,name='home'),
    path('about/',include('about.urls')),
    path('project/', include('project.urls')),
    path('blog/', include('blog.urls')),
]

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

about/models.py
from django.db import models

# Create your models here.

blog/models.py
from django.db import models

# Create your models here.
class Blog(models.Model):
    title = models.CharField(max_length=200)
    summary = models.CharField(max_length=500)
    text = models.TextField()
    image = models.ImageField(upload_to='blog/images/')
    date = models.DateField()
    time = models.TimeField()

    def __str__(self):
        return self.title

home/models.py
from django.db import models

# Create your models here.

project/models.py
from django.db import models

# Create your models here.
class Project(models.Model):
    title = models.CharField(max_length=100)
    summary = models.CharField(max_length=300)
    text = models.TextField()
    image = models.ImageField(upload_to='project/images/')
    date = models.DateField()
    live = models.URLField(blank=True)
    github = models.URLField(blank=True)

    def __str__(self):
        return self.title

about/views.py
from django.shortcuts import render

# Create your views here.
def about(request):
    return render(request,'about/about.html')

blog/views.py
from django.shortcuts import render,get_object_or_404
from .models import Blog

# Create your views here.
def all_blogs(request):
    blogs = Blog.objects.order_by('-date','-time')
    return render(request,'blog/all_blogs.html',{'blogs':blogs})

def detail(request,blog_id):
    blog = get_object_or_404(Blog,pk=blog_id)
    return render(request,'blog/detail.html',{'blog':blog})

home/views.py
from django.shortcuts import render
from project.models import Project
from blog.models import Blog

# Create your views here.
def home(request):
    pjs = Project.objects.order_by('-date')
    blogs = Blog.objects.order_by('-date','-time')
    return render(request,'home/home.html',{'pjs':pjs,'blogs':blogs})

project/views.py
from django.shortcuts import render,get_object_or_404
from .models import Project

# Create your views here.
def all_projects(request):
    pjs = Project.objects.order_by('-date')
    return render(request,'project/all_projects.html',{'pjs':pjs})

def detail(request,project_id):
    pj = get_object_or_404(Project,pk=project_id)
    return render(request,'project/detail.html',{'pj':pj})

templates/about/about.html
{% extends 'home/base.html' %}
{% load static %}

{% block title %}
About me | ryckee
{% endblock %}

{% block content %}
<div class="row justify-content-center">
    <div class='col-12 col-md-3'>
        <img src="{% static 'about/me.jpg' %}" width='100%'><br>
        <br>
        <div class='text-center'>
            <h2>ryckee</h2>
            <hr>
            <p>ryckee.xing@gmail.com</p>
            <a href="https://github.com/imryckee"><img src="{% static 'about/github.jpg' %}" width='60px'></a>
            <a href="{% static 'about/resume.pdf' %}"><img src="{% static 'about/resume.jpg' %}" width='60px'></a>
        </div>
        <br>
    </div>
    <div class='col-12 col-md-6'>
        <div>
            <h1>About me</h1>
            <hr>
            <p>Hi, my name is ryckee.</p>
            <p>I'm a software developer living in China.</p>
        </div>
        <div>
            <h1>My skills</h1>
            <hr>
            <p>TBC</p>
        </div>
    </div>
</div>
<div class="text-center">
    
    
    
    
    
    
</div>
{% endblock %}

templates/blog/all_blogs.html
{% extends 'home/base.html' %}

{% block title %}
Ryckee's blogs
{% endblock %}

{% block content %}
<div class="text-center">
    <h1>Blogs</h1>
    <h2>Ryckee has written {{blogs.count}} blog{{ blogs.count|pluralize}}.</h2>
    <br>
</div>
<div class='row justify-content-center'>
    <div class='col-12 col-md-6'>
        {% for blog in blogs %}
        <div class="card">
            <a href='{% url "blog:detail" blog.id %}'><img src="{{ blog.image.url }}" width='100%'></a>
            <div class="card-body">
                <h2><a href='{% url "blog:detail" blog.id %}'>{{ blog.title }}</a></h2>
                <p>{{ blog.date|date:'F d , Y' }}</p>
                <p class="card-text">{{ blog.summary }}</p>
            </div>
        </div>
        <br>
        {% endfor %}
    </div>
    <div class='col-12 col-md-3'>
        <div class="card">
            <div class="card-body">
                <h4>topics</h4>
                <hr>
                <h5>TBC</h5>
            </div>
        </div>
        <br>
        <div class="card">
            <div class="card-body">
                <h4>tags</h4>
                <hr>
                <h5>TBC</h5>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/blog/detail.html
{% extends 'home/base.html' %}

{% block title %}
{{ blog.title }} | ryckee
{% endblock %}

{% block content %}
<div class="row justify-content-center">
    <div class='col-12 col-md-8'>
        <a href="{{ blog.image.url }}" target="_blank"><img src="{{ blog.image.url }}" width='100%'></a><br>
        <br>
        <div class='text-center'>
            <h2>{{ blog.title }}</h2>
            <p>{{ blog.time|time:'H:i' }} , {{ blog.date|date:'F d , Y' }}</p>
            <em>{{ blog.summary }}</em><br>
            <br>
        </div>
        <p>{{ blog.text|safe }}</p>
    </div>
</div>
{% endblock %}

templates/home/base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel='icon' type='image/png' href="{% static 'home/logo.png' %}">
    <title>{% block title %}{% endblock %}</title>

    <!-- Custom CSS -->
    <link rel="stylesheet" href="{% static 'home/custom.css' %}">
</head>

<body>
    <nav class="navbar navbar-expand-md navbar-light">
        <div class='container'>
            <a class="navbar-brand" href="{% url 'home' %}">
                <img src="{% static 'home/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
                Ryckee
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'project:all_projects' %}">Projects</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'blog:all_blogs' %}">Blogs</a>
                    </li>
                </ul>
                <a href="{% url 'about' %}" class="btn btn-info my-2 my-sm-0">About</a>
            </div>
        </div>
    </nav>

    <div class="container" id='main'>
        <br>
        {% block content %}{% endblock %}
        <br>
    </div>
    

    <footer class="py-2 bg-dark">
        <div class="text-center">
            <p class='text-white-50'>Ryckee © 2020 | Powered by Django </p>
            <a href="http://www.beian.miit.gov.cn" class='text-white'>豫ICP备20010029号</a>
        </div>
    </footer>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
        integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
        crossorigin="anonymous"></script>
</body>

</html>

templates/home/home.html
{% extends 'home/base.html' %}
{% load static %}

{% block title %}
Ryckee's personal website
{% endblock %}

{% block content %}
<div class="row align-items-center">
    <div class='col-md-6 col-lg-4'>
        <img src="{% static 'about/me.jpg' %}" width='100%'>
    </div>
    <div class="col-md-6 col-lg-4">
        <h1><a href='{% url "about" %}' class="text-dark">About me</a></h1>
        <hr>
        <p>Hi, my name is ryckee.</p>
        <p>I'm a software developer living in China.</p>
        <p>Here is my personal website.</p>
        <br>
        <a href="https://github.com/imryckee"><img src="{% static 'about/github.jpg' %}" width='75px'></a>
        <a href="{% static 'about/resume.pdf' %}"><img src="{% static 'about/resume.jpg' %}" width='75px'></a>
    </div>
</div>
<br>

<a href='{% url "project:all_projects" %}' class="text-dark">
    <h1 class="d-inline">Projects</h1>
</a>
<hr>
<div class="row">
    {% for pj in pjs %}
    <div class="col-md-6 col-lg-4">
        <a href='{% url "project:detail" pj.id %}'><img src="{{ pj.image.url }}" width='100%'></a>
        <h2><a href='{% url "project:detail" pj.id %}'>{{ pj.title }}</a></h2>
        <p>{{ pj.date|date:'F , Y' }}</p>
        <p>{{ pj.summary }}</p>

        {% if pj.live %}
        <a href='{{pj.live}}' class="btn btn-primary">Live</a>
        {% endif %}
        {% if pj.github %}
        <a href='{{pj.github}}' class="btn btn-primary">Source code</a><br>
        {% endif %}
        <br>
    </div>
    {% endfor %}
</div>
<br>

<h1><a href='{% url "blog:all_blogs" %}' class="text-dark">Blogs</a></h1>
<hr>
<div class="row">
    {% for blog in blogs %}
    <div class="col-md-6 col-lg-4">
        <a href='{% url "blog:detail" blog.id %}'><img src="{{ blog.image.url }}" class="mb-2" width='100%'></a>
        <h2><a href='{% url "blog:detail" blog.id %}'>{{ blog.title }}</a></h2>
        <p>{{ blog.date|date:'F d , Y' }}</p>
        <p>{{ blog.summary }}</p>
    </div>
    {% endfor %}
</div>
{% endblock %}

templates/project/all_projects.html
{% extends 'home/base.html' %}

{% block title %}
Ryckee's projects
{% endblock %}

{% block content %}
<div class="text-center">
    <h1>Projects</h1>
    <br>
</div>
<div class='row justify-content-center'>
    {% for pj in pjs %}
    <div class='col-12 col-md-5'>
        <div class="card">
            <a href='{% url "project:detail" pj.id %}'><img src="{{ pj.image.url }}" width='100%'></a>
            <div class="card-body">
                <h2><a href='{% url "project:detail" pj.id %}'>{{ pj.title }}</a></h2>
                <p>{{ pj.date|date:'F , Y' }}</p>
                <p class="card-text">{{ pj.summary }}</p>
                
                {% if pj.live %}
                <a href='{{pj.live}}' class="btn btn-primary" target="_blank">Live</a>
                {% endif %}
                {% if pj.github %}
                <a href='{{pj.github}}' class="btn btn-primary" target="_blank">Github</a>
                {% endif %}
            </div>
        </div>
        <br>
    </div>
    {% endfor %}
</div>
{% endblock %}

templates/project/detail.html
{% extends 'home/base.html' %}

{% block title %}
{{ pj.title }} | ryckee
{% endblock %}

{% block content %}
<div class="row justify-content-center">
    <div class='col-12 col-md-8'>
        <a href="{{ pj.image.url }}" target="_blank"><img src="{{ pj.image.url }}" width='100%'></a><br>
        <br>
        <div class='text-center'>
            <h2>{{ pj.title }}</h2>
            <p>{{ pj.date|date:'F , Y' }}</p>
            <em>{{ pj.summary }}</em><br>
            <br>
            {% if pj.live %}
            <a href='{{pj.live}}' class="btn btn-primary">Live</a>
            {% endif %}
            {% if pj.github %}
            <a href='{{pj.github}}' class="btn btn-primary">Source code</a><br>
            {% endif %}
        </div>
        <p>{{ pj.text|safe }}</p>
    </div>
</div>
{% endblock %}